### ISSUE TITLE
Delete Account

### ISSUE THREAD

**Issue by rickbau5** [uidaho/squireproject#10]
Add method for users to delete their account.

**Comment by brec9824** [comment]
@uidaho/lambda Hey I am setting up deletion of a user plus everything connected to them, but I am not to sure how to handle projects they created. Any thoughts about what to do with the projects? Because I am thinking I will have to figure out away to pass it to someone else thats a member or just delete it.

**Comment by rickbau5** [comment]
Implement a voting system so members can vote for a new project lead. Jk 😉 I say just nuke the project. The alternatives require more work than is probably necessary...

**Comment by brec9824** [comment]
Delete account was added in pull #147
