### ISSUE TITLE
Make search work on project page

### ISSUE THREAD

**Issue by brandonjank** [uidaho/squireproject#49]
Ideally should filter the entries on the page in real time and client side. Javascript can be used to toggle css elements as visible or not.

**Comment by rickbau5** [comment]
@drop-table-lol status? You still on this?

**Comment by rickbau5** [comment]
@uidaho/lambda i'm assuming @drop-table-lol isn't working on this, he's doing settings stuff with eric. unassigning him. 

Also re the original post, I don't think that's going to work with pagination unfortunately. In pagination only the entries for the current page are sent to the client so we wouldn't be able to filter all elements in real time. We probably could tweak the paginator to have all the entries and pass that along into the view. Thought thinking about that, we should probably create a new light weight version of the project to pass to the view, like without the body attached (since we're not even using it in the list view) to cut down on the amount of data being sent to the client.

**Comment by brandonjank** [comment]
Cleaning up issues, closing unimplemented/unclaimed feature request.
